import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}

export const sampleQuestions = [
	{
		type: "slider",
		questionNumber: "1",
		questionText: "Rate your interest in architecture:",
		defaultValue: 30,
		maxValue: 100,
		stepValue: 1,
	},
	{
		type: "text",
		questionNumber: "2",
		questionText: "What aspects of architecture interest you the most?",
		placeholder: "Enter your answer here...",
	},
	{
		type: "radio",
		questionNumber: "3",
		questionText: "Which architectural style do you prefer?",
		options: [
			{ value: "modern", label: "Modern" },
			{ value: "classical", label: "Classical" },
			{ value: "contemporary", label: "Contemporary" },
		],
	},
	{
		type: "checkbox",
		questionNumber: "4",
		questionText: "Select all areas you'd like to learn more about:",
		options: [
			{ value: "design", label: "Architectural Design" },
			{ value: "history", label: "Architectural History" },
			{ value: "sustainability", label: "Sustainable Architecture" },
		],
	},
];
export const surveys = [
	{
		id: "emp-sat-1",
		title: "Employee Satisfaction Survey",
	},
	{
		id: "bus-trip-1",
		title: "Business Trip Feedback",
	},
	{
		id: "train-feed-1",
		title: "Training Feedback",
	},
];

export const surveyJson = {
	survey: [
		{
			title: "Office Party Feedback",
			fields: [
				{
					name: "overallEnjoyment",
					label: "How much did you enjoy the office party?",
					type: "slider",
					required: true,
					options: null,
					icon: null,
					multiline: null,
					min: 1,
					max: 10,
				},
				{
					name: "eventDesign",
					label: "How would you rate the design and theme of the event?",
					type: "multiple",
					required: true,
					options: ["Excellent", "Good", "Average", "Poor", "Very Poor"],
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "decorationsSatisfaction",
					label: "How satisfied were you with the decorations?",
					type: "slider",
					required: true,
					options: null,
					icon: null,
					multiline: null,
					min: 1,
					max: 5,
				},
				{
					name: "favoriteDesignElement",
					label: "What was your favorite design element of the party?",
					type: "text",
					required: false,
					options: null,
					icon: null,
					multiline: true,
					min: null,
					max: null,
				},
				{
					name: "activitiesEngagement",
					label: "How engaging were the activities planned during the party?",
					type: "multiple",
					required: true,
					options: ["Very Engaging", "Engaging", "Neutral", "Not Engaging"],
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "eventTheme",
					label: "Did the event theme enhance your experience?",
					type: "checkbox",
					required: true,
					options: null,
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "foodAndBeverage",
					label: "How would you rate the food and beverage options?",
					type: "slider",
					required: true,
					options: null,
					icon: null,
					multiline: null,
					min: 1,
					max: 5,
				},
				{
					name: "musicAndEntertainment",
					label: "How satisfied were you with the music and entertainment?",
					type: "multiple",
					required: true,
					options: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied"],
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "venueSuitability",
					label: "Was the venue suitable for the event?",
					type: "multiple",
					required: true,
					options: ["Perfect", "Good", "Adequate", "Inadequate"],
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "eventDuration",
					label: "Was the duration of the event appropriate?",
					type: "multiple",
					required: true,
					options: ["Too Short", "Just Right", "Too Long"],
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "networkingOpportunities",
					label: "Did the event provide good opportunities for networking?",
					type: "checkbox",
					required: false,
					options: null,
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "improvementSuggestions",
					label: "What improvements would you suggest for future events?",
					type: "text",
					required: false,
					options: null,
					icon: null,
					multiline: true,
					min: null,
					max: null,
				},
				{
					name: "futureParticipation",
					label: "Would you attend similar events in the future?",
					type: "checkbox",
					required: true,
					options: null,
					icon: null,
					multiline: null,
					min: null,
					max: null,
				},
				{
					name: "additionalComments",
					label: "Any additional comments or feedback?",
					type: "text",
					required: false,
					options: null,
					icon: null,
					multiline: true,
					min: null,
					max: null,
				},
			],
		},
	],
};
