import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
	title: "AI Survey Generator",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body className="h-screen w-screen">
				<main
					style={{
						backgroundImage: `url("/Waves.png")`,
						backgroundRepeat: "no-repeat",
						backgroundSize: "cover",
						backgroundPositionX: "-65px",
						backgroundAttachment: "fixed",
					}}
					className="flex min-h-screen flex-col items-center justify-center bg-primary-main"
				>
					{children}
				</main>
			</body>
		</html>
	);
}
